preludeorg/build

src/lib/commands/create-variant-command.tsx
src/lib/lang/go.ts
src/lib/lang/index.ts

@mireaulf  @gerbsec move you PR here

Add codemirror support for go

---

src/lib/commands/create-variant-command.tsx
src/lib/lang/c.ts
src/lib/lang/cs.ts
src/lib/lang/go.ts
src/lib/lang/index.ts
src/lib/lang/swift.ts
src/lib/lang/types.ts

This PR refactors the way languages are defined to make it easier to add new ones and extend the existing.

refactor: add language type and convert classes to objects

---

README.md

Update README to link to prelude docs for the quick start steps

chore: Update README with quickstart that links to docs

---

src/components/terminal/focusable.tsx
src/components/terminal/terminal-list.tsx
src/components/terminal/terminal.tsx
src/hooks/terminal-store.tsx
src/hooks/use-config.tsx

This PR address some bugs found in the focus state and keyboard commands

fix: address some issues in focus state

---

src/components/ds/button/button.module.css
src/components/ds/button/button.tsx
src/components/ds/dialog/confirm-dialog.tsx
src/components/ds/dialog/dialog.module.css
src/components/editor/control-panel.module.css
src/components/editor/control-panel.tsx
src/components/overlays/servers/servers.module.css
src/components/overlays/servers/servers.tsx
src/components/reload-prompt/reload-prompt.module.css
src/components/reload-prompt/reload-prompt.tsx
src/components/terminal/variant-results.module.css
src/components/terminal/variant-results.tsx
src/components/welcome/welcome.module.css
src/components/welcome/welcome.tsx
src/styles/core/colors.css
src/styles/core/typography.css

This PR is a WIP as I still need to fix the download and decline functions. I need to consult @kenrick on this issue.

ds: add button component

---

src/components/ds/accordion/accordion-list.tsx
src/components/ds/accordion/accordion.module.css
src/components/ds/button/button.module.css
src/components/ds/button/button.tsx
src/components/ds/button/icon-button.module.css
src/components/ds/button/icon-button.tsx
src/components/ds/dialog/confirm-dialog.tsx
src/components/ds/dialog/dialog.module.css
src/components/editor/control-panel.tsx
src/components/editor/editor.module.pcss
src/components/editor/window.tsx
src/components/overlays/overlay.module.css
src/components/overlays/overlay.tsx
src/components/terminal/variant-results.module.css
src/components/terminal/variant-results.tsx

This PR adds the icon button component with a similar intent style as the buttons.

ds: add Icon button component

---

apps/build/src/components/editor/window.tsx
apps/build/src/components/overlays/security-tests/security-tests.tsx
apps/build/src/lib/commands/list-variants-command.tsx

Only show lock icon when test is immutable and update open variant message

fix: show lock when test is immutable and update open variant message

---

apps/build/src/components/overlays/security-tests/security-tests.tsx
apps/build/src/components/overlays/verified-tests/verified-tests.tsx

This PR updates the descriptions in the overlays

refactor: update copy

---

apps/build/.eslintrc.cjs
apps/build/package.json
apps/build/src/components/editor/editor.tsx
apps/build/tsconfig.eslint.json
apps/build/tsconfig.json
apps/build/tsconfig.node.json
apps/build/tsconfig.vite.json
packages/eslint-config-custom/index.js
packages/eslint-config-custom/package.json
packages/tsconfig/README.md
packages/tsconfig/base.json
packages/tsconfig/package.json
packages/tsconfig/vite.json

This PR moves the tsconfig and eslint config into packages.
This way they can be shared between apps.

chore: move ts and eslint config into packages

---

apps/platform/src/components/app.tsx
apps/platform/src/components/nav/nav.tsx

This PR removes the extra build icon in nav bar

hotfix: remove extra build icon

---

packages/core/package.json

This PR bumps @theprelude/sdk to the latest version

chore: bump sdk version to latest

---

apps/build/src/components/status-bar/status-bar.tsx
apps/build/src/components/terminal/terminal.tsx
apps/build/src/components/terminal/welcome-message.tsx
apps/platform/package.json
apps/platform/src/components/header/header.module.css
apps/platform/src/components/header/header.tsx
packages/core/package.json
packages/core/src/hooks/use-config.tsx
packages/core/src/lib/emitter.ts
packages/core/src/main.ts
packages/core/src/stores/auth-store.ts

This PR moves the import and export credentials from the Build status bar to the platform header.

move import and export credentials to the header

---

apps/build/src/components/terminal/commands.module.css
apps/build/src/components/terminal/handle-change-message.tsx
apps/build/src/components/terminal/terminal.tsx
apps/build/src/components/terminal/welcome-message.tsx
apps/build/src/lib/commands/use-command.tsx
apps/platform/src/components/app.tsx
apps/platform/src/components/header/header.module.css
apps/platform/src/components/header/header.tsx
packages/core/src/hooks/use-config.tsx
packages/core/src/lib/api.ts
packages/core/src/stores/auth-store.ts
packages/ds/src/components/button/icon-button.module.css
packages/ds/src/components/forms/input.tsx

This PR auto creates a new user account if one doesn't exist with a random handle
https://user-images.githubusercontent.com/760470/206296334-c32ab094-03d1-4a38-a426-a8c5aeb19187.mp4

feat: auto create account on first visit

---

apps/build/package.json
packages/core/package.json

This PR fixes a regex issue in safari caused by the zod package.

hotfix: safari regex issue

---

apps/platform/src/components/header/header.module.css
apps/platform/src/components/header/header.tsx

This PR adds a user card with the account id to the user dropdown

feat: add user card to dropdown

---

apps/platform/index.html
apps/platform/vite.config.ts

I am trying to fix the issue David ran into ( seen below) 
This is my first attempt in this PR, but I can't seem to download the PWA version to see how it looks. Thoughts on these changes so far @kenrick

fix: adjust PWA title

---

apps/welcome/src/components/app.module.css
apps/welcome/src/components/app.tsx

This PR sets up the preliminary format for the welcome screen. I did not include the button / border variables because I see you beat me to it. Let me know if there is anything I am missing in this PR.

feat: prelim formatting for welcome screen

---

apps/platform/src/components/header/header.tsx

This PR auto expands the account popover when an anon account enters the app.

feat: auto expand account popover for anon users

---

apps/platform/src/components/header/header.tsx

fix for https://github.com/preludeorg/build/issues/244

fix: proper change handle message

---

apps/platform/.env
apps/platform/.env.staging

This PR updates the service URL to the new address Patrick posted in Builders

fix: updating the service URL

---

apps/build/src/components/app.module.css
apps/build/src/components/app.tsx
apps/build/src/components/browser/browser.tsx
apps/build/src/components/browser/verified-tests.tsx
apps/build/src/components/overlays/overlays.tsx
apps/build/src/components/status-bar/status-bar.tsx

Add a sidebar that contains the VSTs available to the current user

---

apps/build/src/components/editor/window.tsx

This PR changes the tab name to the rule of the test

feat: change tab name to be rule

---

apps/build/src/hooks/editor-store.ts
packages/core/package.json

This PR bumps the SDK version
Closes #262

chore: update sdk

---

apps/platform/src/components/banner/banner.module.css
apps/platform/src/components/banner/banner.tsx

I aligned it to match the header padding as well

Feat: adding a learn more link in the banner

---

apps/build/src/components/browser/verified-tests.tsx
packages/ds/src/components/accordion/accordion.module.css
packages/ds/src/components/accordion/accordion.tsx
packages/ds/src/components/dialog/confirm-dialog.tsx
packages/ds/src/components/dialog/dialog.module.css

This is my suggestion and working version to delete tests. Had to work around our current set up of things and could be looked back at to simplify later. Just wanted to get something in.

working version for delete Test

---

apps/build/src/components/browser/verified-tests.tsx
packages/core/src/lib/api.ts
packages/ds/src/components/accordion/accordion.module.css
packages/ds/src/components/accordion/accordion.tsx
packages/ds/src/components/dialog/confirm-dialog.tsx
packages/ds/src/components/dialog/dialog.module.css

support deleting user created tests

---

apps/build/package.json
apps/build/src/components/app.tsx
apps/build/src/components/browser/create-test.tsx
apps/build/src/components/browser/verified-tests.tsx
apps/build/src/components/driver/driver.module.css
apps/build/src/components/driver/driver.ts
apps/build/src/components/editor/control-panel.tsx
apps/build/src/components/results/results.tsx
apps/build/src/components/welcome/welcome-block.tsx
apps/build/src/components/welcome/welcome.module.css
apps/build/src/components/welcome/welcome.tsx
apps/build/src/hooks/intro-store.ts
apps/build/src/hooks/use-open-test.ts
apps/build/src/hooks/use-tab.ts
packages/ds/src/components/accordion/accordion-list.tsx
packages/ds/src/components/accordion/use-accordion.ts
packages/ds/src/components/notifications/notifications.tsx

This PR adds a intro flow to build with 4 steps.

build welcome flow

---

apps/build/src/components/browser/verified-tests.tsx

This PR is in response to the feedback @makk94 gave last night!

Feat: close test tab once test is deleted

---

apps/build/src/components/browser/verified-tests.tsx
apps/build/src/components/editor/control-panel.tsx
apps/build/src/components/editor/window.tsx
apps/build/src/components/results/results.module.css
apps/build/src/components/results/results.tsx

This PR fixes a bug thats causes the editor contents to reset when the build button is clicked.

fix: editor resets when build button is clicked
